
    - name: Setup Prompt
      ansible.builtin.shell: set-prompt mysql

    - name: Install the MySQL package
      ansible.builtin.dnf:
        name: mysql-server
        state: present

    - name: restart MySQL and enable the service
      ansible.builtin.service:
        name: mysqld
        state: restarted
        enabled: yes

    - name: setting up the root command
      ansible.builtin.shell:
        mysql_secure_installation --set-root-pass ExpenseApp@1